
services:

  backend:
    build:
      context: ./backend

    container_name: judgex-backend

    ports:
      - "5000:5000"

    env_file:
      - ./backend/.env

    depends_on:
      - judge-worker

    restart: unless-stopped

    networks:
      - judgex-network


  frontend:
    build:
      context: ./frontend

    container_name: judgex-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - judgex-network


  judge-worker:
    build:
      context: ./judge-worker

    container_name: judgex-judge-worker

    ports:
      - "7000:7000"

    env_file:
      - ./judge-worker/.env

    volumes:
      - ./judge-workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

    networks:
      - judgex-network


networks:
  judgex-network:
    driver: bridge